### ISSUE TITLE
App Wont Work (505 Error and other issues)

### ISSUE THREAD

**Issue by qubeley10032** [Cybrarist/Zakaty#2]
Hi, I installed the app using docker, but I keep getting a 505 Error, and cant go beyond the login screen.. I'm not sure why..
The site for the gold API doesnt seem to be working also, I tried using an API from another, but that didnt work, neither did leaving it blank.
I also had to add the DNS to the container because there were some name resolution errors and thee app wouldn't install..

Ive attached the docker-compose.yml file in case that helps. Thanks

```
services:
  zakaty:
    image: cybrarist/zakaty:latest
    ports:
      - 16580:80
    environment:
      DB_CONNECTION: sqlite
     APP_TIMEZONE: Asia/Colombo
     APP_URL: http://localhost:16580
     ASSET_URL: http://localhost:16580
      EXCHANGE_RATE_API_KEY: <got-a-proper-api-key>
      PRECIOUS_METAL_PRICE_API_KEY: 
    volumes:
      - ./database:/app/database/sqlite
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      n65-zakathy:
        ipv4_address: 10.65.0.10
networks:
  n65-zakathy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
```

**Comment by Cybrarist** [comment]
did you use two different API keys from the mentioned services or only one from gold api ? i was able to run the container using your settings (without network stuff)

if yes, try to run `php artisan optimize:clear`  and restart the container after setting up the keys ( they are both required). 

if it didn't work, please reach out with your container log and laravel log (available on storage/logs/laravel-date) on discord.

note: unless you are running the app on your device directly, the app and asset url must be change to the host IP or domain name.

**Comment by Cybrarist** [comment]
my apologies, after double checking it was indeed not working on another machine.

i pushed a fixed and it should be working now, please repull the latest image and it should be fine

**Comment by qubeley10032** [comment]
I got the exchange API without an issue, but the gold API site does not work, so its blank

I tried with the updated image, but it still won't work, it wan'ts o download some packages<
```
65-zakat-calculator  |   - Downloading spatie/laravel-health (1.33.0)
65-zakat-calculator  |   - Downloading shuvroroy/filament-spatie-laravel-health (v2.3.5)
```

but is unable to resolve the url

```
65-zakat-calculator  |     Failed to download spatie/laravel-health from dist: curl error 6 while downloading https://api.github.com/repos/spatie/laravel-health/zipball/2c79b9ad26d37e361689b6df87fe4aba680a3827: Could not resolve host: api.github.com
```
(that's why I tried adding the DNS in the container, but I still get the same error)
The login page is like this,

![Image](https://github.com/user-attachments/assets/9347737d-bf9c-46ff-bd09-4864512f7788)

I have added the port to UFW

**Comment by Cybrarist** [comment]
ok, that's weird it for composer.

but anyway, you need to change the app url and asset url to the url that you access.

if you access 192.168.1.5 then they should be http://192.168.1.5

**Comment by qubeley10032** [comment]
Hi,
I did the changes, but now I get an error 500, like in [this issue ](https://github.com/Cybrarist/Zakaty/issues/3).
The registration woks, then error 500. I clear the cache (or use incognito) and get a login & try, again error 500.

![Image](https://github.com/user-attachments/assets/a614e203-2dc3-4eda-985e-ef38ff3f6526)

This was in the logs, if it helps..
```
   ErrorException 

  Undefined array key "gold_price_24"

  at app/Helpers/CacheHelper.php:45

     41▕                 'silver_price_24', ])

     42▕                 ->pluck("value", "name")

     43▕                 ->toArray();

     44▕ 

  ➜  45▕             return min($price_for_gold_24_and_silver_24['gold_price_24'] * 85,

     46▕                 $price_for_gold_24_and_silver_24['silver_price_24'] * 595);

     47▕ 

     48▕         });

     49▕     }

  1   app/Helpers/CacheHelper.php:45

      Illuminate\Foundation\Bootstrap\HandleExceptions::{closure:Illuminate\Foundation\Bootstrap\HandleExceptions::forwardsTo():255}("Undefined array key "gold_price_24"", "/app/app/Helpers/CacheHelper.php")

      +3 vendor frames 

  5   app/Helpers/CacheHelper.php:37

      Illuminate\Support\Facades\Facade::__callStatic("remember")

   INFO  Clearing cached components and Blade icons.  

      +3 vendor frames 

  5   app/Helpers/CacheHelper.php:37

      Illuminate\Support\Facades\Facade::__callStatic("remember")

   INFO  Caching framework bootstrap, configuration, and metadata.  

  config ........................................................ 27.88ms DONE

  events ......................................................... 1.62ms DONE

  routes ........................................................ 20.76ms FAIL

   LogicException

  Unable to prepare route [storage/{path}] for serialization. Another route has already been assigned name [storage.local].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:248

    244▕             $route->name($this->generateRouteName());

    245▕ 

    246▕             $this->add($route);

    247▕         } elseif (! is_null($symfonyRoutes->get($name))) {

  ➜ 248▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");

    249▕         }

    250▕ 

    251▕         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());

    252▕

      +34 vendor frames 

  35  artisan:13

      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

   INFO  Caching components and Blade icons.  

  Caching components ............................................. 1.02ms DONE

  Caching Blade icons .......................................... 136.69ms DONE

   INFO  Octane installed successfully.
```


Thanks

**Comment by Cybrarist** [comment]
ok, i will implement another provider.

**Comment by Cybrarist** [comment]
should be fixed with the last update.
